// duel_art.dart — composes Duel's card faces from BUNDLED Flutter assets.
//
// Unlike the other games (which paint their art from scratch at runtime), Duel
// ships real image assets — a front-face template with a transparent art
// window, one painted illustration per creature, and ornate back faces — under
// assets/duel/ (generated by tool/generate_duel_assets.py). This file loads
// them with rootBundle, layers illustration → template → text with a Canvas,
// and returns encoded PNGs for TesseraController.registerAtlas: Flutter assets
// referenced from SDL.
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

// Geometry of tool/generate_duel_assets.py's 512x768 template.
const int cardW = 512;
const int cardH = 768;
const Rect _artWindow = Rect.fromLTRB(52, 118, 460, 448);
const Rect _nameBanner = Rect.fromLTRB(40, 44, 472, 102);
const Rect _textBox = Rect.fromLTRB(44, 476, 468, 664);
const Rect _bottomBand = Rect.fromLTRB(40, 682, 472, 726);
const Offset _costGem = Offset(448, 73);
const Offset _attackGem = Offset(66, 704);
const Offset _healthGem = Offset(446, 704);

/// Raw bytes of a bundled asset (handed straight to registerAtlas /
/// registerSound for assets used as-is, e.g. the card back or a WAV).
Future<Uint8List> loadAssetBytes(String key) async {
  final data = await rootBundle.load(key);
  return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
}

Future<ui.Image> _loadAssetImage(String key) async {
  final codec = await ui.instantiateImageCodec(await loadAssetBytes(key));
  return (await codec.getNextFrame()).image;
}

ui.Image? _template; // the shared front frame, decoded once

void _text(Canvas c, String s, Offset center, double size, Color color,
    {FontWeight weight = FontWeight.w700,
    FontStyle style = FontStyle.normal,
    double maxWidth = double.infinity,
    List<Shadow> shadows = const []}) {
  final tp = TextPainter(
    text: TextSpan(
      text: s,
      style: TextStyle(
        color: color,
        fontSize: size,
        fontWeight: weight,
        fontStyle: style,
        height: 1.25,
        shadows: shadows,
      ),
    ),
    textAlign: TextAlign.center,
    textDirection: TextDirection.ltr,
  )..layout(maxWidth: maxWidth);
  tp.paint(c, center - Offset(tp.width / 2, tp.height / 2));
}

/// One finished card front: illustration behind the template's transparent art
/// window, then name, mana cost, attack/health and a flavor line over it.
Future<Uint8List> composeCardFace({
  required String artKey,
  required String name,
  required int cost,
  required int attack,
  required int health,
  required String flavor,
}) async {
  _template ??= await _loadAssetImage('assets/duel/card_front.png');
  final art = await _loadAssetImage('assets/duel/$artKey');

  final rec = ui.PictureRecorder();
  final c = Canvas(rec);

  // Illustration first — the template's art window is transparent, so the
  // frame overdraws everything but the window.
  c.drawImageRect(
    art,
    Rect.fromLTWH(0, 0, art.width.toDouble(), art.height.toDouble()),
    _artWindow.inflate(6),
    Paint()..filterQuality = FilterQuality.high,
  );
  c.drawImage(_template!, Offset.zero, Paint());

  const gold = Color(0xFFF0DCA8);
  const dark = Color(0xFF2A2418);
  final emboss = [
    const Shadow(color: Color(0xCC000000), offset: Offset(0, 2), blurRadius: 3)
  ];

  _text(c, name, _nameBanner.center.translate(0, 1), 40, gold,
      maxWidth: _nameBanner.width - 90, shadows: emboss);
  _text(c, '$cost', _costGem, 44, Colors.white, shadows: emboss);
  _text(c, '$attack', _attackGem, 44, Colors.white, shadows: emboss);
  _text(c, '$health', _healthGem, 44, Colors.white, shadows: emboss);

  _text(c, 'Creature', _bottomBand.center.translate(0, 1), 24,
      gold.withValues(alpha: 0.85),
      weight: FontWeight.w500);
  _text(c, flavor, _textBox.center, 27, dark,
      weight: FontWeight.w500,
      style: FontStyle.italic,
      maxWidth: _textBox.width - 56);

  final img = await rec.endRecording().toImage(cardW, cardH);
  final png = await img.toByteData(format: ui.ImageByteFormat.png);
  img.dispose();
  art.dispose();
  return png!.buffer.asUint8List();
}
