// lua_ttt.dart — "Lua Tic-Tac-Toe": the one example whose game logic does NOT
// live in Dart. The whole game — rules, animation beats, labels, sounds — is
// assets/ttt/game.lua, run by the engine's embedded Lua VM; its assets come
// from the TSAB bundle assets/ttt/ttt.tsb (generated by
// tool/generate_ttt_assets.py). This screen is the minimal host: it loads the
// bundle + script into the engine, then forwards board taps as Lua events and
// lets the engine play whatever state sequences the script returns.
//
// Deliberately not a GameController (game.dart): that framework owns the
// reducer and the scene queue, both of which live inside the script here.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_tessera/flutter_tessera.dart';

class LuaTicTacToePage extends StatefulWidget {
  const LuaTicTacToePage({super.key});

  static const String title = 'Lua Tic-Tac-Toe';
  static const String subtitle = 'The whole game is a Lua script in the engine';
  static const IconData icon = Icons.tag;

  @override
  State<LuaTicTacToePage> createState() => _LuaTicTacToePageState();
}

class _LuaTicTacToePageState extends State<LuaTicTacToePage> {
  TesseraController? _controller;
  bool _ready = false;
  String? _error;

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  Future<void> _onCreated(TesseraController c) async {
    _controller = c;
    c.setLight(const TesseraLightData(
      dir: [-0.35, -1.0, -0.45],
      color: [1.0, 0.97, 0.9],
      intensity: 1.1,
      ambient: [0.34, 0.36, 0.4],
    ));
    c.setQuality(const TesseraQualityData(shadows: TesseraShadowMode.map));
    c.setTiming(const TesseraTimingData(
      addS: 0.3,
      removeS: 0.35,
      moveS: 0.4,
      tileS: 0.3,
      cameraS: 0.8,
    ));

    try {
      // The bundle feeds tessera.asset(...); the script registers its own defs
      // at load time and queues its {name="start"} event for the first tick.
      final bundle = await rootBundle.load('assets/ttt/ttt.tsb');
      await c.loadLuaBundle(
          bundle.buffer.asUint8List(bundle.offsetInBytes, bundle.lengthInBytes));
      await c.runLuaGame(await rootBundle.loadString('assets/ttt/game.lua'));
    } catch (e) {
      if (mounted) setState(() => _error = '$e');
      return;
    }
    await c.start();
    if (mounted) setState(() => _ready = true);
  }

  Future<void> _onTapDown(TapDownDetails d) async {
    final c = _controller;
    if (c == null || !_ready) return;
    // The script owns all rules; the host only translates a tap into a board
    // coordinate. Occupied cells, misses and mid-animation taps are the
    // script's / engine's problem (extra events just queue).
    final pick = await c.pick(d.localPosition.dx, d.localPosition.dy);
    if (pick == null || !pick.hitTile) return;
    c.sendLuaEvent('tap', [pick.tileX.toDouble(), pick.tileY.toDouble()]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(LuaTicTacToePage.title)),
      body: Stack(
        children: [
          Positioned.fill(
            child: GestureDetector(
              onTapDown: _onTapDown,
              child: TesseraView(onCreated: _onCreated),
            ),
          ),
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.black.withValues(alpha: 0.0),
                    Colors.black.withValues(alpha: 0.55),
                  ],
                ),
              ),
              padding: const EdgeInsets.fromLTRB(16, 24, 16, 16),
              child: Text(
                _error ??
                    (!_ready
                        ? 'starting…'
                        : 'Tap a square to play — every rule and animation beat '
                            'comes from assets/ttt/game.lua'),
                style: const TextStyle(fontSize: 13),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
